### ISSUE TITLE
SearchCards method error

### ISSUE THREAD

**Issue by denisvlasevgdc** [LeanKit/LeanKit.API.Client#11]
Hello.

I use LeanKit.API to take existing cards on LeanKit board. Everything worked fine, but since Saturday morning I have had an error: Unable to process the response from the API:

9/18/2017 1:54:47 PM | Search InRecentArchive: LeanKit.API.Client.Library.Exceptions.LeanKitAPIException: Unable to process the response from the API.
   at LeanKit.API.Client.Library.RestSharpCommandProcessor.ValidateResponse(IRestResponse`1 response, ILeanKitAccountAuth leanKitAccountAuth, IRestRequest request) in C:\_projects\LeanKit.API.Client\LeanKit.API.Client.Library\RestSharpCommandProcessor.cs:line 289
   at LeanKit.API.Client.Library.RestSharpCommandProcessor.RetryRequest(IRestRequest request, ILeanKitAccountAuth accountAuth, RestClient client) in C:\_projects\LeanKit.API.Client\LeanKit.API.Client.Library\RestSharpCommandProcessor.cs:line 241
   at LeanKit.API.Client.Library.RestSharpCommandProcessor.Process[T](ILeanKitAccountAuth accountAuth, IRestRequest request) in C:\_projects\LeanKit.API.Client\LeanKit.API.Client.Library\RestSharpCommandProcessor.cs:line 201
   at LeanKit.API.Client.Library.LeanKitClient.SearchCards(Int64 boardId, SearchOptions options) in C:\_projects\LeanKit.API.Client\LeanKit.API.Client.Library\LeanKitClient.cs:line 296
   at LeanConsole.LeanKitInterface.SearchForNewCardsNumbers(String title, Boolean SearchInBacklog, Boolean SearchInRecentArchive, Boolean SearchInOldArchive, DateTime dtStart, DateTime dtEnd, DateTime dt0, DateTime dt1) in C:\Projects\KundewebApps\LeanConsole\LeanConsole\LeanKitInterface.cs:line 82
   at LeanConsole.LeanKitInterface.Init(Int64 boardId) in C:\Projects\KundewebApps\LeanConsole\LeanConsole\LeanKitInterface.cs:line 35
   at LeanConsole.LeanKitInterface..ctor(Int64 boardId) in C:\Projects\KundewebApps\LeanConsole\LeanConsole\LeanKitInterface.cs:line 117
   at LeanConsole.Worker.Run() in C:\Projects\KundewebApps\LeanConsole\LeanConsole\Worker.cs:line 27

Do you know anything to fix this error?

**Comment by reverentgeek** [comment]
I've not been able to reproduce the issue with `SearchCards`. Can you provide your account host name, board ID, and the `SearchOptions` you are using with this method?

**Comment by denisvlasevgdc** [comment]
Hello,

account host name = fujitsudk
board ID = 73304588
"searchOptions":
                {
                    "SearchInOldArchive":true,
                    "IncludeExternalId":true,
                    "AddedAfter":"06/17/2017",
                    "AddedBefore":"09/18/2017",
                    "Page":2
                }

Currently response from API takes about 40 sec. Last week it takes about 2-3 sec

**Comment by denisvlasevgdc** [comment]
Hello

I think it's secure information for publish it here. Maybe I have to open incident in support?

**Comment by reverentgeek** [comment]
Hi,

I don't believe this is an error with the API client itself, but some issues we were having with search results taking longer than normal to return. If you are still having an issue, please contact support@leankit.com.
